<?php
/**
 * A module which takes in entityform results from a user
 * Then it translates these results into drush commands
 * Ultimately the user can set, in this module, what results turn into what drush commands
 */

/**
* Implements hook_help()
*
* Displays help and module information
*
* @param path
*            which path of the site we're using to display help
*
* @param arg
*            array that holds the current path returned from arg() function
 */

function enformactionlinker_help($path, $arg){
	switch ($path){
	   case "admin/help#enformactionlinker":
	      return '<p>' . t("Take in results from entity form and convert them into drush recipe commands.") . '</p>';
	   break;
	}
}


/*
Any time entityform_entityform_insert is called, I should know that there is a new form answer
When that happens, I get the results (entity form get submissions)
Those are passed in to a function in enformactionlinker and compared to pre-determined results
			ultimately those predetermined results are decided by the user ahead of time, and linked to drush recipe files
Those results call different drush recipe files
 */

/**
 * Implements hook_entityform_insert().
 */
function enformactionlinker_entity_insert($entity, $type) {
 dpm($entity); // just testing to make sure it triggers when a new form is submitted


  $entityProperties = array();
  $entityProperties = get_object_vars($entity);
  dpm($entityProperties);
  $convertFormResults = array();
  $convertFormNames = array();
  $nameOfFile;
  foreach($entityProperties as $key => $value) { // this loop checks the results of the form
  	 if (strpos($key, 'field_') === 0 && isset($value['und'][0]['value'])) { // and finds and stores the form values in convertFormResults
    	$convertFormResults[] = $value['und'][0]['value'];
      $convertFormNames[] = $key; } // it also gets the name of each value in convertFormNames (this is where drush commands are stored)
     if (strpos($key, 'type') === 0) { // also the name of the form becomes the file name
      $nameOfFile = $value;
     }
  }
 dpm($convertFormResults);
 dpm($convertFormNames);
 $filePath = "/tmp/";
 $nameOfFile .= ".drecipe";
 dpm($nameOfFile);

 $recipeFile = fopen($filePath . $nameOfFile, "a"); // creating the file, currently just at data/Drupal7

 /**
  * The module functions as intended for any number of true / false files, so long as certain conventions are followed
  * I will establish the conventions on the page where the admin chooses where the path should be set (form name convention, question name convention, limitations on question types)
  */

 for($i = 0; $i < count($convertFormResults); $i++)
 {
  if($convertFormResults[$i] == 1)
  {
    $convertFormNames[$i] = substr($convertFormNames[$i], 6);
    fwrite($recipeFile, $convertFormNames[$i] . "\r\n");
  }
 }

}